In [7]:
# Số vô hướng (Scalar)
# Sử dụng Tensor để tạo một số vô hướng
# Phương trình y = 20x + 200
### x and y là số vô hướng
# Pytorch
import torch

a = torch.tensor(20)
b = torch.tensor(200)
print("diện tích x = 50 --> giá nhà y = a*50+b = ", a*50+b)

# Numpy
import numpy as np

a = np.array(20)
b = np.array(200)
print("diện tích x = 50 --> giá nhà y = a*50+b = ", a*50+b)

diện tích x = 50 --> giá nhà y = a*50+b =  tensor(1200)


In [11]:
# Vector
x = torch.tensor([1, 2, 2.1, 2.5, 3.3, 4])
x

tensor([1.0000, 2.0000, 2.1000, 2.5000, 3.3000, 4.0000])

In [12]:
# Các thuộc tính của Vector

In [13]:
# Độ dài
print('length of vector: ', x.size()) # or len(x)

# Định dạng của vector
print('Vector type:', x.dtype)

# Tổng của các phần tử 
print("sum of vector: ", x.sum())

# Trung bình các phần tử
print("mean of vector: ", x.mean())

# Giá trị nhỏ nhất
print("min of vector: ", x.min())

# Giá trị lớn nhất
print("max of vector: ", x.max())

length of vector:  torch.Size([6])
Vector type: torch.float32
sum of vector:  tensor(14.9000)
mean of vector:  tensor(2.4833)
min of vector:  tensor(1.)
max of vector:  tensor(4.)


In [14]:
# Các phép tính trên vector

In [17]:
x = torch.tensor([1, 2, 1.5, 1.8, 1.9])
y = torch.tensor([1.1, 2.2, 1.2, 1.6, 1.7])
print("x + y: ", x + y)
print("x - y: ", x - y)
print("x * y: ", x * y)

x + y:  tensor([2.1000, 4.2000, 2.7000, 3.4000, 3.6000])
x - y:  tensor([-0.1000, -0.2000,  0.3000,  0.2000,  0.2000])
x * y:  tensor([1.1000, 4.4000, 1.8000, 2.8800, 3.2300])


In [18]:
x = torch.tensor([1, 2, 1.5, 1.8, 1.9])
print("x + 5: ", x + 5)
print("x - 5: ", x - 5)
print("x * 5: ", x * 5)

x + 5:  tensor([6.0000, 7.0000, 6.5000, 6.8000, 6.9000])
x - 5:  tensor([-4.0000, -3.0000, -3.5000, -3.2000, -3.1000])
x * 5:  tensor([ 5.0000, 10.0000,  7.5000,  9.0000,  9.5000])


In [19]:
# MA TRẬN

In [22]:
# Các thuộc tính của ma trận
A = torch.tensor([[1, 2, 3],
                 [3, 2, 1]])
# shape of matrix A
print(A)
A.size()

tensor([[1, 2, 3],
        [3, 2, 1]])


torch.Size([2, 3])

In [23]:
# Các phép tính trên Ma trận

In [29]:
# Hai ma trận có cùng kích thước chúng ta có thể thực hiện các phép cộng, trừ,
# tích hadamard (hoặc elementi-wise)

# Trên pytorch chúng ta có thể tính tích hadamard của hai ma trận đơn giản như sau:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1]])

B = torch.tensor([[2, 1, 2], 
                  [1, 3, 0]])
print('A*B: \n ',A*B)
# Tương tự với các phép cộng và trừ
print("A-B: \n", A-B)
print("A+B: \n", A+B)

A*B: 
  tensor([[2, 2, 6],
        [3, 6, 0]])
A-B: 
 tensor([[-1,  1,  1],
        [ 2, -1,  1]])
A+B: 
 tensor([[3, 3, 5],
        [4, 5, 1]])


In [30]:
# Index

In [39]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1],
                  [4, 2, 2]])

# Truy cập ma trận con từ 2 dòng đầu tiên và 2 cột đầu tiên.
A[:2, :2]


tensor([[1, 2],
        [3, 2]])

In [38]:
# Truy cập ma trận có các dòng chẵn
A[::2, :]

tensor([[1, 2, 3],
        [4, 2, 2]])

In [44]:
import torch
A = torch.tensor([[1, 2, 3], 
                  [3, 2, 1],
                  [4, 2, 2]])

# Truy cập một index cụ thể , ví dụ dòng 0, 2 của ma trận
A.index_select(0, torch.tensor([0, 2]))
# Trong công thức trên 0 là chiều mà ta sẽ lấy, tensor([0, 2]) là các index ta sẽ lấy từ chiều 0.

tensor([[1, 2, 3],
        [4, 2, 2]])

In [45]:
# Tensor

In [54]:
A = torch.tensor([[[1, 2, 3], 
                  [3, 2, 1]],
                  [[2, 1, 2], 
                  [1, 3, 0]]])

# Kích thước của tensor
print("shape of A: " , A.size())

# Số chiều 
print("total dim: ", A.ndim)

# Định dạng dữ liệu
print("dtype: ", A.dtype)

shape of A:  torch.Size([2, 2, 3])
total dim:  3
dtype:  torch.int64


In [55]:
# Các phép tính trên tensor

In [59]:
import torch

A = torch.randn([2, 3, 4])
B = torch.randn([2, 4, 2])

# Tích giữa 2 tensor
(A@B)

tensor([[[-2.7581, -3.0571],
         [-1.5879, -2.1221],
         [ 2.0965,  2.3269]],

        [[-0.2220, -4.7969],
         [-0.0219, -0.9093],
         [-2.4037,  2.2392]]])

In [58]:
# Ngoài ra chúng ta có thể tính tích hadamard giữa 2 tensors A và B
import torch

A = torch.randn([2, 3, 4])
B = torch.randn([2, 3, 4])

# Tích hadamard giữa 2 tensor
(A*B)

tensor([[[-0.7530,  0.2640, -0.0887,  0.0492],
         [ 0.5080, -1.7922,  0.1810, -0.1645],
         [-0.3252, -0.4344,  0.9739,  1.3017]],

        [[-0.3580,  0.1178,  0.4047,  1.2828],
         [ 1.0662,  0.3550, -0.1652, -0.9828],
         [-0.3565, -0.2496,  0.5135,  0.2065]]])

In [64]:
# Phép cộng
import torch

A = torch.randn([2, 3, 4])
B = torch.randn([2, 3, 4])
(A+B).size()
# Phép trừ
(A-B).size()

torch.Size([2, 3, 4])

In [70]:
# Index
import torch

# Khởi tạo ma trận A kích thước m, n, p = 2, 3, 4
A = torch.randn([2, 3, 4])
print(A)
# Truy cập ma trận đầu tiên 
A[:1, :, :]

tensor([[[-0.7842, -1.6750, -0.3562,  0.9552],
         [-0.6934,  1.2724,  0.5250,  0.2856],
         [-0.2017,  1.0379,  0.1112,  0.6586]],

        [[-0.7521, -0.7426, -0.3627,  0.6057],
         [-0.2568,  0.9903, -1.5363, -1.1700],
         [-0.1931, -0.7917,  0.1837,  1.7721]]])


tensor([[[-0.7842, -1.6750, -0.3562,  0.9552],
         [-0.6934,  1.2724,  0.5250,  0.2856],
         [-0.2017,  1.0379,  0.1112,  0.6586]]])

In [71]:
# Truy cập ma trận đầu tiên và chỉ lấy dòng từ 1 tới 3
A[0][1:3, :]

tensor([[-0.6934,  1.2724,  0.5250,  0.2856],
        [-0.2017,  1.0379,  0.1112,  0.6586]])

In [75]:
# Truy cập tương ứng với các chiều m, n, p lần lượt index đầu tiên, 2 index đầu tiên, và index thứ 3.
A[:1, :2, 3]

tensor([[0.9552, 0.2856]])

In [76]:
# Tích giữa ma trận với vector

In [77]:
# Giả sử bạn đã biết được các biến đầu vào gồm: diện tích và số phòng ngủ như các dòng của ma trận bên dưới:
import torch

X = torch.tensor([[100, 120, 80, 90, 105, 95], 
                  [2, 3, 2, 2, 3, 2]])

In [78]:
# Và hệ số hồi qui tương ứng với với chúng lần lượt là w=(10,100).
# Khi đó giá nhà có thể được ước lượng bằng tích y=X⊤w

In [79]:
w = torch.tensor([[10], [100]])
y = X.T@w
y

tensor([[1200],
        [1500],
        [1000],
        [1100],
        [1350],
        [1150]])

In [80]:
# Tích vô hướng

In [81]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([2, 3, 4])
x.dot(y)

tensor(20)

In [82]:
# Khái niệm chuẩn

In [ ]:
# Chưa hiểu lắm, học lại sau